### ISSUE TITLE
fix natverse travis build

### ISSUE THREAD

**Issue by jefferis** [natverse/natverse#10]
This is currently failing because hex sticker needs image magick to be installed. I think we should probably remove this logo generation function because a) it feels like it is targeted at developers rather than end users b) it doesn't work for end users at the moment (the png can't be found by here).

**Comment by SridharJagannathan** [comment]
@jefferis Fixed via ca30080, the `hexSticker` package is currently under Suggests and hence normal users would not be installing it. But you are right that this function needs to be adapted and possibly moved to https://github.com/jefferis/nat.devtools
Can you please move the repo to `natverse`, so I will move this functionality there and close the issue after that.

**Comment by SridharJagannathan** [comment]
On second thoughts, since @alexanderbates  has already made logos in hex format the usage of this functionality will be minimal, but in future if someone wants to make logos programatically then they can look at how it is made by the logo generation function in the updated `nat.devtools`, Also the output png is stored in the presentation folder under the name natverse_logo.png. I will adapt this so that instead of storing somewhere it should display it on the plot viewer.

**Comment by jefferis** [comment]
I have moved `nat.devtools` to the `natverse` organisation.

**Comment by jefferis** [comment]
And updated URLs accordingly.

**Comment by SridharJagannathan** [comment]
Removed functionality for hex logos via 47765e5 and will be moved to `nat.devtools` and implemented via PR: https://github.com/natverse/nat.devtools/pull/1
